### ISSUE TITLE
Add more SourceProcessor like replace

### ISSUE THREAD

**Issue by lumixraku** [ShellWen/v8_killer#13]
Is it possible add more SourceProcessor? Now only insert before and after. 
could add a processor just replace the whole file?

**Comment by ShellWen** [comment]
Yes, but I currently don't have lots of time focused on this. However, I will get it done.

**Comment by ShellWen** [comment]
We plan to implement two replacement methods: one based on regular expressions and the other based on text. Is this okay?

**Comment by ShellWen** [comment]
We plan to implement two replacement methods: one based on regular expressions and the other based on text. Is this okay? @lumixraku

**Comment by lumixraku** [comment]
It's cool with me
