### ISSUE TITLE
launcher 的示例有问题

### ISSUE THREAD

**Issue by ghostflyby** [ShellWen/v8_killer#3]
```bash
V8_KILLER_CONFIG_FILE_PATH=path_to_config.toml v8_killer_launcher /use/bin/node path_to_target.js
```
不会执行后面的代码文件，因为 https://github.com/ShellWen/v8_killer/blob/638dfe48d5fa2b5c28033325c64e79fbbd3ed995/crates/launcher/src/main.rs#L11

只解析了第一个参数，这个参数 `/use/bin/node` 拼写错误。

建议 launch  直接接受 Args 或者可迭代物作为参数，而不是接受第一个参数为 String 然后自己解析
```rust
Command::new("exe”).args(std::env::args().skip(2)).spawn();
```

**Comment by ShellWen** [comment]
已经看到了，很抱歉犯了这种低级错误

另外这个问题是因为之前的遗留代码，后面重构了之后这部分没改，我会尽快处理
