### ISSUE TITLE
Further enhance macOS support

### ISSUE THREAD

**Issue by ShellWen** [ShellWen/v8_killer#9]
We need to further support macOS, with the following steps:
- [x] `core` support (by 8133a85)
- [x] `launcher` support

Furthermore, we need to explore further the different behaviors when SIP is enabled or disabled, and whether the target program is code-signed or not.

**Comment by mp1repo** [comment]
Looking forward to support for macOS system.

**Comment by ShellWen** [comment]
Because I don't have any macOS devices, I need to seek support from the community for this aspect. Without further assistance, this issue may not progress.

**Comment by Steve-xmh** [comment]
I'm trying to implement macOS support, you can check it on #28 for progress.

**Comment by ShellWen** [comment]
Closed #28.
